### PR TITLE
Fix codes and update version to 1.7

### PR DESCRIPTION
**Pull request by mistzzt**
* Change to a new format and add support for old schematic file as well as some human-readable text for this change
* Remove redundant codes
* Fix for Tiled plugin (servers that are not using default tile provider)
* Use keyword instead of type name for FCL types
* Remove some unreasonable short command aliases
* Fix some weird command argument parsing

- [x] Support for old version
- [x] Command test
- [x] ~~Expression for both clipboard and real world~~

### CODE REVIEW

**Comment by AnzhelikaO** [comment]
Why do you want to remove aliases? You want people to suffer with 'schematic load' instead of 'sc l'? Also you need to update description on forum.

**Comment by mistzzt** [comment]
The link on the forum was pointed to an old version, so I wont update these descriptions until i finish my work.
Also, i thought that some command like /sc is not reasonable. Maybe a plugin like **ShortCommand** can help you.

**Comment by mistzzt** [comment]
I'll consider to readd sth like '//p1' or '//p2' instead of '/p1' or '/p2'. The command '//schematic' has an alias '//schem' before; the '/sc' may be confusing.

**Comment by AnzhelikaO** [comment]
Yeah i'm using my own aliases, but i thought it would be useful to have them in plugin itself... Also i would like to see credits for my changes later.

**Comment by AnzhelikaO** [comment]
Why did you remove //scale? It's usefull thing that scales clipboard. Please return it.

**Comment by AnzhelikaO** [comment]
Also why did you remove feature to evaluate file blocks in //paste? If i want to paste only part of my file i want to be able to. Please return it as well.

**Comment by mistzzt** [comment]
I just want re-implement the //scale command.
As for the argument of //paste, which is also mentioned in this pr `Expression for both clipboard and real world`, I have not consider to add it yet. Maybe you can have your own fork of this plugin.

**Pull request merged**
